armnn-swig mod and pyarmnn removal
Freescale/meta-freescale-ml pull request #13
Opened 2021-09-21 21:48 UTC by chrisdimich

2021-09-21 22:38 UTC, otavio requested changes

2021-09-21 22:38 UTC, otavio commented on recipes-devtools/armnn-swig/armnn-swig.inc
> +FILES:${PN} += "${datadir}/swig/*/*"
Drop it; just the -dev should be added.

2021-09-22 18:08 UTC, chrisdimich commented
@otavio I fixed this and also added an update to the packagegroup.

2021-09-22 18:16 UTC, otavio approved these changes

2021-09-22 18:16 UTC, merged